require: rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Max: 128
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Exclude:
    - 'lib/mrkt/concerns/connection.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Max: 6

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
