language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.6.0
addons:
  code_climate:
    repo_token: 45cd2174f49b570406e294ff393d456c4ae8532cf16dd6430abb06d8a0722a28
before_install:
  - gem update --system
after_success:
  - bundle exec codeclimate-test-reporter
